baseURL = "/" # is used as base for absURL and is overridden by HUGO_BASEURL env var
languageCode = "en"
title = "Learn it my way"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 6
enableRobotsTXT = true
disableKinds = ["taxonomy","taxonomyTerm"]
googleAnalytics = "UA-110144291-1"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "David's learning experiences as a self-taught software developer"
  shareImage = "https://res.cloudinary.com/developerdavo/image/upload/f_auto,w_1200/v1590954325/learnitmyway/header.png"
  author = "David"
  about = "Thanks for visiting Learn it my way! I created this website so I could share my learning experiences as a self-taught software developer."
  twitter = "https://twitter.com/learnitmyway"
  github = "https://github.com/learnitmyway"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true