baseURL = "/"
languageCode = "en"
title = "Learn it my way"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 6
enableRobotsTXT = true

[params]
  featured_image = "/images/equations-on-blackboard.jpg"
  author = "Developer Davo"
