baseURL = "/"
languageCode = "en"
title = "Learn it my way"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
Paginate = 6
enableRobotsTXT = true

[params]
  author = "Developer Davo"
  background_color_class = "bg-dark-blue"
