baseURL = "/"
languageCode = "en-us"
title = "Learn it my way"
theme = "ananke"

Paginate = 6
enableRobotsTXT = true

[params]
  featured_image = "/images/equations-on-blackboard.jpg"
  author = "Developer Davo"
