[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  HUGO_VERSION = "0.49"
  HUGO_ENV = "production"
  NODE_ENV = "production"

[context.production.environment]
  HUGO_BASEURL = "https://learnitmyway.com/"