[build]
  publish = "public"
  command = "npm run build"
  HUGO_BASEURL = "https://preview--learnitmyway.netlify.com/"

[build.environment]
  HUGO_VERSION = "0.72.0"
  HUGO_ENV = "production"
  NODE_ENV = "production"

[context.staging.environment]
  HUGO_BASEURL = "https://staging--learnitmyway.netlify.com/"

[context.production.environment]
  HUGO_BASEURL = "https://learnitmyway.com/"